config/routes.rb
Rails.application.routes.draw do


  resources :blogs, only: [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'
  namespace :managment do
    resources :kbs
    resources :blogs
    resources :accounts do
      resources :transactions do
        member do
          patch :comfirm
        end
      end
    end
    resources :transactions do
      member do
        patch :comfirm
      end
    end
  end
  resources :welcome, only: [:new, :create]
  resources :managment
  #knowlege base and forum starts here
  resources :kbs, only: [:index, :show]

  #accounts  and accounts api and transactions starts here
  resources :accounts do
    resources :transactions
  end
  namespace :api do
    namespace :v1 do
      post "accounts/new_transaction", to: "accounts#new_transaction"
    end
  end

  #tests to be reworked
  resources :deposits
  resources :balances, except: [:show]
  get 'balances/history',  to: 'balances#history'

  namespace :balance do
    resources :withdraw, only: [:new, :create]
    resources :depositor, only: [:new, :create]
  end

  #dynamic rerouting
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end

  authenticated :managment do
    root "managment#index"
  end

  #admins starts here
  devise_for :managments
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :pages, only: [:show]
  ActiveAdmin.routes(self)

  #hompage
  root 'welcome#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/kb.rb
class Kb < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :managment
end

app/models/managment.rb
class Managment < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  # :confirmable, :lockable,s
has_many :kbs
has_many :blogs
end

app/controllers/kbs_controller.rb
class KbsController < ApplicationController
  layout "blog"
  before_action :find_kbs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_managment!, except: [:index, :show]
  def index
    @kbs = Kb.all.order('created_at DESC')
  end

  def show
    @kbs = Kb.all.order('created_at DESC')
  end

  private
  def find_kbs
    @kb = Kb.friendly.find(params[:id])
  end

  private
    def kbs_params
      params.require(:kb).permit(:title, :body, :questio, :managment_id, :slug)
    end
end

app/controllers/managment/accounts_controller.rb
class Managment::AccountsController < ApplicationController
  layout "managment"
  before_action :find_account, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_managment!
  def index
    @accounts = Account.all.order('created_at DESC')
  end

  def show
  end


  def edit

  end

  def update
    if @account.update(account_params)
      redirect_to managment_account_path(@account), notice: "Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to managment_accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def find_account
    @account = Account.friendly.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:account_number, :balance, :bitcoin_address, :user_id, :slug)
  end
end

app/controllers/managment/blogs_controller.rb
class Managment::BlogsController < ApplicationController
  layout "managment"
  before_action :find_blogs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_managment!
  def index
    @blogs = Blog.all.order('created_at DESC')
  end

  def show

  end
  def new
    @blog = current_managment.blogs.build
  end

  def create
    @blog = current_managment.blogs.build(blogs_params)
    if @blog.save
      redirect_to managment_blogs_path(@blog), notice: "Blog Successfully Created"
    else
      render 'new'
    end
  end
  def edit
  end

  def update
    if @blog.update(blogs_params)
      redirect_to managment_blogs_path(@blog)
    else
      render 'edit'
    end
  end

  def destroy
    if @blog.destroy
      redirect_to managment_blogs_path
    end
  end

  private
  def find_blogs
    @blog = Blog.friendly.find(params[:id])
  end

  private

    def blogs_params
      params.require(:blog).permit(:title, :body, :description, :managment_id, :slug)
    end


end

app/controllers/managment/kbs_controller.rb
class Managment::KbsController < ApplicationController
  layout "managment"
  before_action :find_kbs, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_managment!
  def index
    @kbs = Kb.all.order('created_at DESC')
  end

  def show

  end
  def new
    @kb = current_managment.kbs.build
  end

  def create
    @kb = current_managment.kbs.build(kbs_params)
    if @kb.save
      redirect_to managment_kbs_path(@kb), notice: "knowlegdes Successfully Created"
    else
      render 'new'
    end
  end
  def edit
  end

  def update
    if @kb.update(kbs_params)
      redirect_to managment_kbs_path(@kb)
    else
      render 'edit'
    end
  end

  def destroy
    if @kb.destroy
      redirect_to managment_kbs_path
    end
  end

  private
  def find_kbs
    @kb = Kb.friendly.find(params[:id])
  end

  private

    def kbs_params
      params.require(:kb).permit(:title, :body, :question, :managment_id, :slug)
    end


end

app/controllers/managment/transactions_controller.rb
class Managment::TransactionsController < ApplicationController
  layout "managment"
  before_action :find_transaction, only: [:comfirm,:show, :edit, :update, :destroy]
  before_action :authenticate_managment!
  def index
    @transactions = Transaction.all.order('created_at DESC')

  end

  def show
    @transaction = Transaction.find(params[:id])
  end


  def edit

  end

  def update
    if @transaction.update(transaction_params)
      redirect_to managment_transaction_path(@transaction)
    else
      render 'edit'
    end
  end
  def destroy
    if @transaction.destroy
      redirect_to managment_transactions_path, notice: "deleted"
    end
  end


  def comfirm
    @transaction.update_attribute(:comfirmed_at, Time.now)
    redirect_to managment_transactions_path, notice: "Transaction Confirmed"
  end




  private
  def find_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:transaction_number, :amount, :comfirmed_at, :transaction_type, :account_id)
  end
end

app/controllers/managment_controller.rb
class ManagmentController < ApplicationController
  layout "managment"
  before_action :authenticate_managment!
  before_action :find_managment, only: [:show, :dashboard]


  def index
  end
  def dashboard
  end

  def show
  end

  private
  def find_management
    if params[:id].nil?
      @managment = current_managment
    else
      @managment = Managment.find(params[:id])
    end
  end

end

app/helpers/kbs_helper.rb
module KbsHelper
end

app/helpers/managment/blogs_helper.rb
module Managment::BlogsHelper
end

app/helpers/managment/kbs_helper.rb
module Managment::KbsHelper
end

app/views/managment/kbs/_form.html.erb
<%= simple_form_for([:managment, @kb]) do |f| %>
<div class="panel panel-flat">
  <div class="panel-heading">
    <h5 class="panel-title">knowlege Base</h5>
    <div class="heading-elements">
      <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>

              </ul>
            </div>
  </div>
  <div class="panel-body">
  <%= f.error_notification %>
  <fieldset>
    <legend class="text-semibold">
      <i class="icon-file-text2 position-left"></i>
      Enter your information
      <a class="control-arrow" data-toggle="collapse" data-target="#demo1">
        <i class="icon-circle-down2"></i>
      </a>
    </legend>

    <%= f.input :title, placeholder: "Title", class: "form-control" %>
    <%= f.input :question, placeholder: "Important! Type The Question Asked", class: "form-control" %>
    <%= f.input :body, placeholder: "message", class: "form-control",  as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>



  </fieldset>
  <div class="text-right">
    <%= f.submit :submit, class: "btn btn-success"  do %>
    <i class="icon-arrow-right14 position-right"></i>
    <% end %>
  </div>
<%end%>

app/views/managment/kbs/edit.html.erb
<div class="page-header page-header-default">
  <div class="page-header-content">
    <div class="page-title">
      <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Managment</span> - Edit Account</h4>
    </div>
  </div>


  <div class="breadcrumb-line">
    <ul class="breadcrumb">
      <li><a href="index.html"><i class="icon-home2 position-left"></i> Management</a></li>
      <li class="active">edit New knowlege </li>
    </ul>


    </ul>
  </div>
</div>
<!-- /page header -->
<div class="col-md-8 col-md-offset-2">
  <%= render "form" %>
</div>

app/views/managment/kbs/index.html.erb
<div class="page-header page-header-default">
  <div class="page-header-content">
    <div class="page-title">
      <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Managment</span> - Dashboard</h4>
    </div>
  </div>

  <div class="breadcrumb-line">
    <ul class="breadcrumb">
      <li><a href="index.html"><i class="icon-home2 position-left"></i> Management</a></li>
      <li class="active">Knowledge Base </li>
    </ul>

  </div>
</div>
<!-- /page header -->
<!-- Info blocks -->



					<!-- Questions area -->
					<h4 class="text-center content-group">
						Knowledge Base
						<small class="display-block">View All answered questions and new updates </small>
					</h4>

					<div class="row">
						<div class="col-lg-12">
              <% if Kb.all.exists? %>

              <% @kbs.each do |k| %>
							<!-- Questions list -->

							<div class="panel-group panel-group-control panel-group-control-right">
								<div class="panel panel-white">
									<div class="panel-heading">
										<h6 class="panel-title">
											<a class="collapsed" data-toggle="collapse" href="#<%= k.id %>">
												<i class="icon-help position-left text-slate"></i> <%= k.title %>
											</a>
										</h6>
									</div>

									<div id="<%= k.id %>" class="panel-collapse collapse">
										<div class="panel-body">
                      <%= raw(k.body) %>
										</div>

										<div class="panel-footer panel-footer-transparent">
											<div class="heading-elements">
												<span class="text-muted heading-text">Posted:<%= k.created_at.strftime("%d %b %Y") %></span>

												<ul class="list-inline list-inline-condensed heading-text pull-right">
                          <li> Answered By  <%= current_managment.email %>
                            <li><%= social_share_button_tag(k.title) %></li>

                          </li>
													<li>   <%= link_to edit_managment_kb_path(k), class: "text-muted" do %>

                            <i class=" icon-pencil5 position-left"></i> Edit
                            <% end %>
                          </li>
													<li>
                              <%= link_to managment_kb_path(k), method: :delete, class: "text-muted" do %>
                            <i class="icon-bin2 position-left"></i> Del
                              <%end %>
                          </li>
												</ul>
											</div>
										</div>
									</div>
								</div>
              </div>

              <%end %>
              <% else %>
              <div class="col-md-8 col-md-offset-2" >
              <div class="panel panel-flat">
                <div class="panel-heading">
                  <h6 class="panel-title">No FAQ's</h6>
                  <div class="heading-elements">
                    <ul class="icons-list">
                              <li><a href="#"><i class="icon-cog3"></i></a></li>
                            </ul>
                          </div>
                </div>

                <div class="panel-body">

                  <%= link_to new_managment_kb_path, class: "btn bg-teal btn-block" do %>
                    Create knowledge <i class="icon-comment position-right"></i>

                    <% end %>

                </div>
            </div>
          </div>

            <% end %>

app/views/managment/kbs/new.html.erb
<div class="page-header page-header-default">
  <div class="page-header-content">
    <div class="page-title">
      <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Managment</span> - Edit Account</h4>
    </div>
  </div>


  <div class="breadcrumb-line">
    <ul class="breadcrumb">
      <li><a href="index.html"><i class="icon-home2 position-left"></i> Management</a></li>
      <li class="active">Add New knowlege </li>
    </ul>


    </ul>
  </div>
</div>
<!-- /page header -->
<div class="col-md-8 col-md-offset-2">
  <%= render "form" %>
</div>