config/routes.rb
Rails.application.routes.draw do


  resources :blogs, only: [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'
  namespace :managment do
    resources :kbs
    resources :blogs
    resources :accounts do
      resources :transactions do
        member do
          patch :comfirm
        end
      end
    end
    resources :transactions do
      member do
        patch :comfirm
      end
    end
  end
  resources :welcome, only: [:new, :create]
  resources :managment
  #knowlege base and forum starts here
  resources :kbs, only: [:index, :show]

  #accounts  and accounts api and transactions starts here
  resources :accounts do
    resources :transactions
  end
  namespace :api do
    namespace :v1 do
      post "accounts/new_transaction", to: "accounts#new_transaction"
    end
  end

  #tests to be reworked
  resources :deposits
  resources :balances, except: [:show]
  get 'balances/history',  to: 'balances#history'

  namespace :balance do
    resources :withdraw, only: [:new, :create]
    resources :depositor, only: [:new, :create]
  end

  #dynamic rerouting
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end

  authenticated :managment do
    root "managment#index"
  end

  #admins starts here
  devise_for :managments
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :pages, only: [:show]
  ActiveAdmin.routes(self)

  #hompage
  root 'welcome#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :account_number, use: :slugged

  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :user, presence: true
  validates :balance, presence: true
  validates :bitcoin_address, presence: true, uniqueness: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.account_number = SecureRandom.uuid
    end
  end

#  def auto_increment
  #  @accounts.each do |account|
  #   if account.balance > 0.00
  #    @divider = account.balance * 0.01
  #  end
  #   account.update_attribute(balance: account.balance + @divider)
  # end
  #end


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/balance.rb
class Balance < ApplicationRecord
      belongs_to :user
      has_many :deposits

def self.amount(balance)
      @balance.balance += @deposit.amount
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :blogimg, BlogimgUploader
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :managment
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

end

app/models/depositor.rb
class Depositor < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :message
  attribute :amount
  attribute :nickname,  :captcha  => true

# Declare the e-mail headers. It accepts anything the mail method
# in ActionMailer accepts.

def headers
    {
      :subject => "Deposit Request ",
      :to => "payment@tradebitr.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/kb.rb
class Kb < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :managment
end

app/models/managment.rb
class Managment < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  # :confirmable, :lockable,s
has_many :kbs
has_many :blogs
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :user
  TRANSACTION_TYPES = ["withdraw", "deposit"]
  validates :account, presence: true
  validates :amount, presence: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES}
  validates :transaction_number, presence: true, uniqueness: true
  validates :txhash, presence: true,  uniqueness: true, if: -> {transaction_type == "deposit"}

  def comfirmed?
    !comfirmed_at.blank?
  end

  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end

  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
 has_many :accounts
 has_many :transactions
 has_many :deposits



end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :amount
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@tradebitr.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/withdraw.rb
class Withdraw < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :account_number
  attribute :amount
  attribute :bitcoin_address
  attribute :nickname,  :captcha  => true

# Declare the e-mail headers. It accepts anything the mail method
# in ActionMailer accepts.

def headers
    {
      :subject => "Withdrawal Request ",
      :to => "support@tradebitr.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/kbs_helper.rb
module KbsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/shared/_blog_sidebar.html.erb
<div class="sidebar col-md-3">
  <div class="widget clearfix">
    <div class="banner-widget">
      <a href="https://themeforest.net/user/similaricons/portfolio?ref=SimilarIcons" target="new"><img src="assets/images/uploads/banner.jpg" alt="" class="img-responsive img-thumbnail"></a>
    </div>
  </div><!-- end widget -->

  <div class="widget clearfix">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Login Account</h3>
      </div>
      <div class="panel-body">
        <form class="sidebar-login">
          <input type="text" class="form-control" placeholder="Username">
          <input type="text" class="form-control" placeholder="Password">
          <div class="checkbox">
            <label>
              <input type="checkbox"> &nbsp;&nbsp;Remember me
            </label>
          </div>
          <button type="button" class="btn btn-raised btn-info gr">Login</button>
        </form>
      </div>
    </div>
  </div><!-- end widget -->
</div><!-- end col -->

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer>
    <div class="container">
        <div class="row">
            <!-- Footer Top -->
            <div class="trd-footer-top">
                <!-- About Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-about-widget">
                    <div class="trd-logo-wrapper">

                        <%= image_tag "logo-footer-6.png" %>
                    </div>

                    <p>Earn deposit and cashback bonuses based on your trading activity. Get notified of bonus payments made to your balance in real-time as you trade, right in your dashboard</p>
                </div>
                <!-- End -->

                <!-- Useful Link Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-useful-link-widget">
                    <h3 class="trd-footer-widget-title">Useful Link</h3>

                    <div class="trd-footer-widget-content">
                        <ul>
                          <li>
                            <%= link_to "About Us", page_path("about") %>
                          </li>
                            <li><a href="https://drive.google.com/open?id=0B5jZgQVjo_uQbVNTbWtIZWoyS1U">Company info/White Paper</a></li>
                            <li>
                              <%= link_to "How It Works", page_path("How-it-works") %>
                            </li>
                            <li>
                              <%= link_to "Account", accounts_path %>

                            </li>
                            <li>
                              <%= link_to "Contact Us", "#contact" %>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- End -->

                <!-- Recent Post Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-recent-post-widget">
                    <h3 class="trd-footer-widget-title">Recent Post</h3>

                    <div class="trd-footer-widget-content">
                        <div class="trd-recent-post-wrapper">
                            <!-- Post Item -->
                            <div class="trd-recent-post-item">
                                <h3 class="trd-post-title">
                                    <a href="#">Bitcoin Developers concerned about segwit </a>
                                </h3>

                                <span class="trd-post-date">july 25, 2017</span>
                            </div>
                            <!-- End -->

                            <!-- Post Item -->
                            <div class="trd-recent-post-item">
                                <h3 class="trd-post-title">
                                    <a href="#">Bitcoin Cash Launching Date. Excitment or Loss?</a>
                                </h3>

                                <span class="trd-post-date">August 1, 2017</span>
                            </div>
                            <!-- End -->
                        </div>
                    </div>
                </div>
                <!-- End -->

                <!-- Subscribe For Widget -->
                <div class="col-md-3 col-sm-6 col-xs-12 trd-footer-widget trd-subscribe-widget">
                    <h3 class="trd-footer-widget-title">Subscribe</h3>

                    <div class="trd-footer-widget-content">
                        <p>Let Chat. we promise not to disturb</p>

                        <form action="#">
                            <input type="email" name="trd-subscription" id="trd-subscription" placeholder="Your email">
                            <button type="submit" class="trd-btn">Submit</button>
                        </form>
                    </div>
                </div>
                <!-- End -->
            </div>
            <!-- End -->

            <!-- Footer Bottom -->
            <div class="trd-footer-bottom">
                <div class="trd-footer-menu">
                    <ul>
                      <div class="trd-social-links">
                          <ul>
                              <li class="trd-fb-icon">
                                  <a href="https://facebook.com/tradebitr">
                                      <i class="fa fa-facebook"></i>
                                  </a>
                              </li>
                              <li class="trd-twitter-icon">
                                  <a href="https://twitter.com/tradebitr">
                                      <i class="fa fa-twitter"></i>
                                  </a>
                              </li>

                          </ul>
                      </div>
                    </ul>
                </div>

                <div class="trd-copyright-info">
                    <p>Copyright &copy; 2016 by <a href="http://web.zonia.co" class="trd-author-link">TradeBitr</a></p>
                </div>
            </div>
            <!-- End -->
        </div>
    </div>
    <!-- End -->
</footer>
<!-- FOOTER END -->

app/views/shared/_header.html.erb
<!-- HEADER -->
    <header class="trd-header trd-transparent-header trd-fixed-header">

  <div class="trd-header-bottombar">
  <!-- Navigation Menu start-->
  <nav class="navbar trd-main-menu" role="navigation">
    <div class="container">
      <div class="row">
        <!-- Navbar Toggle -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, class: "navbar-brand "  do %>
          <%= image_tag "logo-header-6.png", class: "logo" %>
          <% end %>
        </div>
        <!-- Logo -->

        <!-- Navbar Toggle End -->
        <div id="nav-menu" class="navbar-collapse trd-menu-wrapper collapse" role="navigation">

          <!-- Menu -->
          <ul class="nav navbar-nav trd-menus">
            <!-- navbar-collapse start-->


            <li class="active">
              <%= link_to "Home",  root_path %>

            </li>
              <% if user_signed_in?  %>
              <li>
                <%= link_to "Account", accounts_path %>

              </li>

              <li>
                <%= link_to "Withdraw", new_balance_withdraw_path %>

              </li>

              <li>
                <%= link_to "Community", kbs_path %>
                <ul class="trd-dropdown-menu">
                    <li>
                      <%= link_to "knowledge base", kbs_path %>
                        <a href="#"> Forums</a>
                        <a href="#"> Blog</a>

                    </li>
                </ul>
              </li>


              <li>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>



                          <% else %>
            <li>
              <%= link_to "About Us", page_path("about") %>
              <ul class="trd-dropdown-menu">
                  <li>
                      <%= link_to "Contact Us",("#contact") %>
                  </li>
              </ul>
            </li>

            <li>
              <%= link_to "Tradebitr's Community", kbs_path %>
              <ul class="trd-dropdown-menu">
                  <li>
                    <%= link_to "knowledge base", kbs_path %>
                      <a href="#"> Forums</a>
                      <a href="#"> Blog</a>

                  </li>
              </ul>
            </li>


            <li>
              <%= link_to "Log In / Sign Up", new_user_session_path %>

            </li>

            <% end %>
            <li>

                  <div class="trd-social-links">
                      <ul class="list-inline">
                          <li class="trd-fb-icon">
                              <a href="https://facebook.com/tradebitr">
                                  <i class="fa fa-facebook"></i>
                              </a>
                          </li>
                          <li class="trd-twitter-icon">
                              <a href="https://twitter.com/tradebitr">
                                  <i class="fa fa-twitter"></i>
                              </a>
                          </li>

                      </ul>
                  </div>
                </li>

          </ul>
          <!-- End -->
        </div>
        <!-- navbar-collapse end-->




    </div>
    <!-- navbar-collapse end-->


    <span class="trd-contact-num">
    Support@tradebitr.com</span>
  </div>
</div>
</nav>
<!-- Navigation Menu end-->
</div>
<!-- End -->
</header>
<!-- HEADER END -->

<!-- HEADER END -->

app/views/shared/_pricing.html.erb
<br>
<br>
<br>
<div class="trd-custom-sec-details">
  <!-- Section: Price -->
  <section id="price" class="section bg-theme">
    <div class="container">

      <!-- Section Header -->
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <header class="text-center">
            <h2 class="section-title underline text-white">Select Best Plan for You</h2>
            <p class="section-subtitle text-white">
                Dear tradebitr members and investors, we are excited to have you on our platform where we would help you make the most of your investment.
            </p>
          </header>
          <br />
          <br />

        </div>
      </div>
      <!-- /Section Header -->

      <!-- Section Content -->
      <div class="row section-content">

        <!-- Plan -->
        <div class="col-md-6 col-sm-6 animated fadeIn wow" data-wow-duration="0.9s">
          <div class="plan">

            <div class="price">
              <span class="dollar">$</span>50+
            </div>

            <h3 class="name text-center">MEMBERS ACCOUNT </h3>

            <ul class="features">
              <li>Earn up to 30% of your deposit in just 28days</li>
              <li>24/7 Support</li>
              <li>Get 30% Cashback </li>
              <li>Get 15% Referral Bonus</li>

            </ul>


            <%= link_to new_user_registration_path, class: "  trd-btn-alt  btn btn-danger " do %>
            <i class="icon fa fa-fw fa-check"></i> <span class="text" style="color: #fff !important;">Select Plan</span>
            <% end %>
          </div>
        </div>
        <!-- /Plan -->



        <!-- /Plan -->

        <!-- Plan -->
        <div class="col-md-6 col-sm-6 animated fadeIn wow" data-wow-duration="0.9s" data-wow-delay="0.4s">
          <div class="plan">


            <div class="price">
              <span class="dollar">$</span>250+
            </div>

            <h3 class="name text-center"I>INVESTORS ACCOUNT </h3>
            <ul class="features">
              <li>Earn up to 80% of your deposit in just 60days.</li>
              <li>24/7 Support</li>
              <li>Get 80% Cashback </li>
              <li>Get 25% Referral Bonus</li>


                       </ul>


            <%= link_to new_user_registration_path, class: "trd-btn trd-btn-alt  btn btn-danger" do %>
            <i class="icon fa fa-fw fa-check"></i> <span class="text" style="color: #fff !important;">Select Plan</span>
            <% end %>
          </div>
        </div>
        <!-- /Plan -->

      </div>
      <!-- /Section Content -->

    </div>
  </section>
</div>
<!-- /Section: Price -->

app/views/shared/_sfooter.html.erb
<div class="stickyfooter">
    <div id="sitefooter" class="container">
        <div id="copyright" class="row">
            <div class="col-md-6 col-sm-12 text-left">
                <p>Tradebitr ® is a designed and registered trademark of <a href="https://www.web.zonia.com/">Tradebitr</a> INC.</p>
            </div>
            <div class="col-md-6 col-sm-12">
                <ul class="list-inline text-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Knowledge Base", kbs_path %></li>
                    <li><%= link_to "Blog", blogs_path %></li>
                    <li><%= link_to "WHite Paper", root_path %></li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/shared/_top.html.erb
<section class="bg">
  
</section>