config/routes.rb
Rails.application.routes.draw do


  resources :blogs, only: [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'
  namespace :managment do
    resources :kbs
    resources :blogs
    resources :accounts do
      resources :transactions do
        member do
          patch :comfirm
        end
      end
    end
    resources :transactions do
      member do
        patch :comfirm
      end
    end
  end
  resources :welcome, only: [:new, :create]
  resources :managment
  #knowlege base and forum starts here
  resources :kbs, only: [:index, :show]

  #accounts  and accounts api and transactions starts here
  resources :accounts do
    resources :transactions
  end
  namespace :api do
    namespace :v1 do
      post "accounts/new_transaction", to: "accounts#new_transaction"
    end
  end

  #tests to be reworked
  resources :deposits
  resources :balances, except: [:show]
  get 'balances/history',  to: 'balances#history'

  namespace :balance do
    resources :withdraw, only: [:new, :create]
    resources :depositor, only: [:new, :create]
  end

  #dynamic rerouting
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end

  authenticated :managment do
    root "managment#index"
  end

  #admins starts here
  devise_for :managments
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :pages, only: [:show]
  ActiveAdmin.routes(self)

  #hompage
  root 'welcome#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/balance.rb
class Balance < ApplicationRecord
      belongs_to :user
      has_many :deposits

def self.amount(balance)
      @balance.balance += @deposit.amount
  end
end

app/controllers/balance/depositor_controller.rb
class Balance::DepositorController < ApplicationController
  def new
  @depositor = Depositor.new
  end

  def create
    @depositor = Depositor.new(params[:depositor])
    @depositor.request = request
    if @depositor.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'cannot send message.'
      render :new
    end
  end
end

app/controllers/balance/withdraw_controller.rb
class Balance::WithdrawController < ApplicationController
  def new
  @withdraw = Withdraw.new
  end

  def create

    @withdraw = Withdraw.new(params[:withdraw])
    @withdraw.request = request
    if @withdraw.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'cannot send message.'
      render :new
    end
  end
end

app/controllers/balances_controller.rb
class BalancesController < InheritedResources::Base

  before_action :find_Balance, only: [  :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @balances = Balance.where(user_id: current_user).order('created_at DESC')

  end
  def history
        @balances = Balance.where(user_id: current_user).order('created_at DESC')
  end

  def show
#    if valid_page?
#   render template: "balances/#{params[:id]}"
 #else
#   render file: "public/404.html", status: :not_found
# end
  end

  def new
    @balance = current_user.balances.build
  end

  def create
    @balance = current_user.balances.build(balance_params)

    if @balance.save
      redirect_to @balance
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @balance.update(balance_params)

  redirect_to @Balance
else
  render 'edit'
end
  end

  def destroy
    @balance.destroy
  end




  private
  def find_Balance
    @balance = Balance.find(params[:id])
  end
  def valid_page?
     File.exist?(Pathname.new(Rails.root + "app/views/balances/#{params[:id]}.html.erb"))
   end
    def balance_params
      params.require(:balance).permit(:balance, :tradeId, :currency, :deposit, :expiration, :status, :tradetype, :entry, :rate, :return )
    end
end

app/helpers/balance/deposit_helper.rb
module Balance::DepositHelper
end

app/helpers/balance/withdraw_helper.rb
module Balance::WithdrawHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<%= simple_form_for(@balance) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :balance %>
<%=    f.input :tradeId %>
  <%=  f.input :currency, :as => :select, :collection => ['USD', 'GB', 'AUD/USD', 'AUD/GB'] %>
    <%=  f.input :deposit %>
    <%=  f.input :expiration %>
    <%=  f.input :status, as: :select, :collection => ["WON", "LOSE"] %>
    <%=  f.input :tradetype %>
    <%=  f.input :entry %>
    <%=  f.input :rate %>
    <%=    f.input :return %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/balances/edit.html.erb
<h1>Editing Balance</h1>

<%= render 'form', balance: @balance %>

<%= link_to 'Show', @balance %> |
<%= link_to 'Back', balances_path %>

app/views/balances/history.html.erb
<%= render "shared/top" %>
<section class="trd-page-breadcumb-header">
    <div class="container">
        <div class="row">
            <h1 class="trd-page-title"> Trade History </h1>
            <div class="trd-breadcumb-wrapper">

            </div>
        </div>
    </div>
</section>
<!-- PAGE HEADER END -->

<!-- PAGE CONTENTS -->
<section class="trd-page-contents-wrapper">
    <div class="container">
        <div class="row">
          <div class="trd-contact-form-wrapper col-md-12  col-sm-6 col-xs-12">
              <h1 class="trd-section-tittle">Trade <span class="trd-highlight-text">History</span></h1>
              <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">History</div>
                <div class="panel-body">
                  <p>Account Trade History</p>
                </div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Trade Id</th>
            <th>Currency</th>
            <th>Amount Invested</th>
            <th>Entry Rate </th>
              <th>Rate</th>
                <th>Entry Time</th>
                  <th>Expiration</th>
                    <th>Status</th>
                      <th>Returns</th>



        </tr>
    </thead>
    <tbody>
            <% @balances.each do |b| %>
            <tr>
              <td>
                <%=b.tradeId %>
              </td>
              <td>
                <%= b.currency %>
              </td>
              <td>
                <%= b.deposit %>
              </td>
              <td>
                <%= b.entry%>
              </td>
              <td>
                <%=b.rate %>
              </td>
              <td>
                <%=b.created_at.strftime("%I:%M %p %b %d") %>
              </td>
              <td>
                <%= b.expiration %>
              </td>
              <td>
                <%= b.status %>
              </td>
              <td>
                <%= b.return%>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
  </div>

</section>

app/views/balances/index.html.erb
<%= render "shared/top" %>


<!-- PAGE HEADER -->
      <section class="trd-page-breadcumb-header">
          <div class="container">
              <div class="row">

                  <div class="trd-breadcumb-wrapper col-md-6">

                      <% @balances.take(1).each do |b| %>
                      <h3> Current Balance ( $ <%= b.balance %>)</h3>
                      <% end %>
                  </div>

          </div>
      </section>
      <!-- PAGE HEADER END -->

      <!-- PAGE CONTENTS -->
      <section class="trd-page-contents-wrapper">
          <div class="container">
              <div class="row">

                  <!-- Sidebar -->
                  <div class="trd-sidebar trd-sidebar-left col-md-3 col-sm-4 col-xs-12">
                      <!-- Widget -->
                      <div class="btcwdgt-price" bw-theme="light" bw-cur="eur"></div>

                      <div class="trd-sidebar-widget trd-pagelink-widget">
                          <ul>
                                <li> Account Updates/History  </li>
                                <% @balances.take(5).each do |balance| %>
                              <li>
                             History   $  <%= balance.balance %>
                              </li>
                              <% end %>


                          </ul>
                      </div>
                      <!-- End -->

                      <!-- Widget -->
                      <div class="trd-sidebar-widget trd-download-widget">
                          <p>View <br>Your <span class="trd-highlight-text">Account History</span> from here</p>
                        
                          <%= link_to "Account history", balances_history_path, class: "trd-btn" %>
                      </div>
                      <!-- End -->
                  </div>
                  <!-- Sidebar End -->

                  <!-- Page Contents -->
                  <div class=" col-md-9 col-sm-8 col-xs-12">
                      <div class="col-md-12 embed-responsive embed-responsive-16by9">

                            <div style="width:100%; max-width:100% !important;" class="btcwdgt-chart"></div>


  </div>





              </div>
                    </div>



          </div>
        </div>
      </section>
      <!-- PAGE CONTENTS END -->
      <section class="trd-page-contents-wrapper">
          <div class="container">
            <h1 class="text-center">Latest News </h1>
              <div class="row">
                <div class="col-md-6 embed-responsive embed-responsive-16by9">
        <div class="btcwdgt-news" bw-cur="eur" bw-theme="light"></div>
        </div>
        <div class="col-md-6 embed-responsive embed-responsive-16by9">
<div class="btcwdgt-forum" bw-theme="light"></div>
</div>
</div>
</div>
</section>

app/views/balances/new.html.erb
<h1>New Balance</h1>

<%= render 'form', balance: @balance %>

<%= link_to 'Back', balances_path %>

app/views/balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Balance:</strong>
  <%= @balance.balance %>
</p>



<%= link_to 'Edit', edit_balance_path(@balance) %> |
<%= link_to 'Back', balances_path %>