config/routes.rb
Rails.application.routes.draw do


  resources :blogs, only: [:index, :show]

  mount Ckeditor::Engine => '/ckeditor'
  namespace :managment do
    resources :kbs
    resources :blogs
    resources :accounts do
      resources :transactions do
        member do
          patch :comfirm
        end
      end
    end
    resources :transactions do
      member do
        patch :comfirm
      end
    end
  end
  resources :welcome, only: [:new, :create]
  resources :managment
  #knowlege base and forum starts here
  resources :kbs, only: [:index, :show]

  #accounts  and accounts api and transactions starts here
  resources :accounts do
    resources :transactions
  end
  namespace :api do
    namespace :v1 do
      post "accounts/new_transaction", to: "accounts#new_transaction"
    end
  end

  #tests to be reworked
  resources :deposits
  resources :balances, except: [:show]
  get 'balances/history',  to: 'balances#history'

  namespace :balance do
    resources :withdraw, only: [:new, :create]
    resources :depositor, only: [:new, :create]
  end

  #dynamic rerouting
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end

  authenticated :managment do
    root "managment#index"
  end

  #admins starts here
  devise_for :managments
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :pages, only: [:show]
  ActiveAdmin.routes(self)

  #hompage
  root 'welcome#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ApplicationRecord
  extend FriendlyId
  friendly_id :account_number, use: :slugged

  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :user, presence: true
  validates :balance, presence: true
  validates :bitcoin_address, presence: true, uniqueness: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.account_number = SecureRandom.uuid
    end
  end

#  def auto_increment
  #  @accounts.each do |account|
  #   if account.balance > 0.00
  #    @divider = account.balance * 0.01
  #  end
  #   account.update_attribute(balance: account.balance + @divider)
  # end
  #end


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
      belongs_to :user
      has_many :deposits

def self.amount(balance)
      @balance.balance += @deposit.amount
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :blogimg, BlogimgUploader
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :managment
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user

end

app/models/depositor.rb
class Depositor < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :message
  attribute :amount
  attribute :nickname,  :captcha  => true

# Declare the e-mail headers. It accepts anything the mail method
# in ActionMailer accepts.

def headers
    {
      :subject => "Deposit Request ",
      :to => "payment@tradebitr.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/kb.rb
class Kb < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :managment
end

app/models/managment.rb
class Managment < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  # :confirmable, :lockable,s
has_many :kbs
has_many :blogs
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :user
  TRANSACTION_TYPES = ["withdraw", "deposit"]
  validates :account, presence: true
  validates :amount, presence: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES}
  validates :transaction_number, presence: true, uniqueness: true
  validates :txhash, presence: true,  uniqueness: true, if: -> {transaction_type == "deposit"}

  def comfirmed?
    !comfirmed_at.blank?
  end

  before_validation :load_defaults
  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end

  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
 has_many :accounts
 has_many :transactions
 has_many :deposits



end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :amount
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@tradebitr.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/withdraw.rb
class Withdraw < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true
  attribute :account_number
  attribute :amount
  attribute :bitcoin_address
  attribute :nickname,  :captcha  => true

# Declare the e-mail headers. It accepts anything the mail method
# in ActionMailer accepts.

def headers
    {
      :subject => "Withdrawal Request ",
      :to => "support@tradebitr.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/deposits_controller.rb
class DepositsController < InheritedResources::Base
  before_action :find_deposit, only: [:show,  :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @deposits = Deposit.where(user_id: current_user).order('created_at DESC')

  end
  def show

  end

  def new
    @deposit = current_user.deposits.build
  end

  def create
    @deposit = current_user.deposits.build(deposit_params)

    if @deposit.save
      user = User.find_by_id(@deposit.user_id)
      deposit = @deposit
      UserDepositMailer.deposit_email(user, deposit).deliver
      redirect_to @deposit
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @deposit.update(deposit_params)

      redirect_to @deposit
    else
      render 'edit'
    end
  end

  def destroy
    @deposit.destroy
  end



  private
  def find_deposit
    @deposit = Deposit.find(params[:id])
  end
  def deposit_params
    params.require(:deposit).permit(:amount, :bitcoin_address)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/balance/deposit_helper.rb
module Balance::DepositHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/kbs_helper.rb
module KbsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/deposits/_form.html.erb
<%= simple_form_for(@deposit) do |f| %>
  <%= f.error_notification %>


    <%= f.input :amount %>
    <%= f.input :bitcoin_address %>



    <%= f.submit :submit, class: "btn btn-success btt" %>

<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<%= render "shared/top" %>
<section class="trd-page-breadcumb-header">
    <div class="container">
        <div class="row">
            <h1 class="trd-page-title">Account Deposits</h1>

        </div>
    </div>
</section>
<section class="trd-page-contents-wrapper">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-center">
              <%= link_to "Make Deposit", new_deposit_path, class: "trd-btn trd-btn-purple" %>
            </div>
          </div>
          <br>
          <br>
          <br>
          <br>  <br>
            <br>  <br>
              <br>
    <% @deposits.each do |deposit| %>
     <div class="col-md-3">
       <div class="alert alert-primary">
         <p class="text-center pb"><%= deposit.created_at.strftime("%d %b %Y")  %></p>
       </div>
     </div>
     <div class="col-md-2">
       <hr />
     </div>

     <div class="col-md-7">
       <div class="alert alert-warning">
         <h4 class="text-center">Deposit Order Recieved </h4><br>
         <p> We have recieved your deposit request of <strong><%= deposit.amount %></strong>
             your account will be credited automatically once confirmed. Thank You <br> You can set a withdrawal request for this deposit after 14 days
           </p>
  </div>
</div>
<% end %>



<br>
</div>
</div>
</section>

app/views/deposits/new.html.erb
<%= render "shared/top" %>
<section class="trd-page-breadcumb-header">
    <div class="container">
        <div class="row">
            <h1 class="trd-page-title">New Deposit</h1>

        </div>
    </div>
</section>
<section class="trd-page-contents-wrapper">
    <div class="container">
        <div class="row">
          <div class="trd-contact-form-wrapper col-md-8 col-md-offset-2 col-sm-6 col-xs-12">
              <h1 class="trd-section-tittle">Deposit <span class="trd-highlight-text"> Request Form</span></h1>
  <div class="trd-contact-form-wrapper">
<%= render 'form', deposit: @deposit %>
</div>
<%= link_to 'Back', deposits_path %>
</div>
</div>
</div>
</section>

app/views/deposits/show.html.erb
<!-- PAGE HEADER -->
<%= render "shared/top" %>
      <section class="trd-page-breadcumb-header">
          <div class="container">
              <div class="row">
                  <h1 class="trd-page-title">Deposit Order</h1>
                  <div class="trd-breadcumb-wrapper">
                    <h2> Deposit of <%= @deposit.amount %></h2>
                  </div>
              </div>
          </div>
      </section>
      <!-- PAGE HEADER END -->

      <!-- PAGE CONTENTS -->
      <section class="trd-page-contents-wrapper">
          <div class="container">
              <div class="row">
                <div class="trd-contact-form-wrapper col-md-8 col-md-offset-2 col-sm-6 col-xs-12">
                    <h1 class="trd-section-tittle">Thank<span class="trd-highlight-text"> You For Your Request.</span> <br></h1>
                       <h3 class="text-center">Ensure to send the amount of <%= @deposit.amount %> USD to this address (Bitcoin )<br>1BQeM4qwHeEviP8JQGDAoqrPfVBVG3cPAs </br> </span></h3>
                       <h3 class="text-center">An Invoice Has been sent to your mail. Do ensure to use it for reference purposes </h3>
                    <h2 class="text-center">Or Contact Us For Other Payment Methods </h2>
                    <br>
                    <div class="col-md-12 text-center">
                    <%= link_to "Other Payment Method", new_balance_depositor_path, class: "trd-btn trd-btn-purple" %>
                  </div>


                </div>
              </div>
            </div>
          </section>